osx_image: xcode8.2
language: objective-c

env:
  matrix:
    - DESTINATION="platform=iOS Simulator,name=iPhone 5s,OS=9.3"
    - DESTINATION="platform=iOS Simulator,name=iPhone 7,OS=10.1"

podfile: Example/Podfile
before_install:
  - gem install cocoapods
  - pod repo update
  - pod install --project-directory=Example

script:
- set -o pipefail 
- xcodebuild build -workspace Example/Example.xcworkspace -scheme Example -destination "$DESTINATION"
- pod lib lint --allow-warnings
